version: '3'
services:
  micro:
    container_name: micro
    image: snowplow/snowplow-micro:1.0.0
    volumes:
      - ./micro:/config
    restart: always
    ports:
      - "9090:9090"
    command: "--collector-config /config/micro.conf --iglu /config/iglu.json"

  web:
    container_name: app
    build: ./app    
    volumes:
      - ./app/:/code
    ports:
        - "8002:80"